server:
  port:8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 3000
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 180000
  redis:
    cache:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        show_sql: true
    open-in-view: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
security:
  jwt:
    token:
      secretKey: ${JWT_KEY}
      expirationMs: ${JWT_EXPIRY}
      refreshExpirationMs: ${REFRESH_EXPIRY}

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: textme-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

fcm:
  certification: ${GOOGLE_APPLICATION_CREDENTIALS}

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    client_secret: ${KAKAO_CLIENT_SECRET}
    scope: ${KAKAO_SCOPE}
    api:
      authorize: ${KAKAO_AUTHORIZE_API}
  dku:
    client_id: ${DKU_CLIENT_ID}
    redirect_uri: ${DKU_REDIRECT_URI}
    client_secret: ${DKU_CLIENT_SECRET}
    scope: ${DKU_SCOPE}
    api:
      base_url: ${DKU_BASE_URL}
      authorize: ${DKU_AUTHORIZE_API}

batch:
  view-count:
    delay: 10000


logging:
  level:
    org.springframework.core:
      LocalVariableTableParameterNameDiscoverer: error
    org.hibernate.SQL: info
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug